[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = true

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#FF5A5F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
